// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Automobilistica.Models
{
    public partial class Carros
    {
        public Carros()
        {
            CarroCliente = new HashSet<CarroCliente>();
            Proposta = new HashSet<Proposta>();
        }

        [Key]
        [Column("CRCDCARRO")]
        public int Crcdcarro { get; set; }
        [Required]
        [Column("CRMODELO")]
        [StringLength(100)]
        [Unicode(false)]
        public string Crmodelo { get; set; }
        [Required]
        [Column("CRFABRICANTE")]
        [StringLength(100)]
        [Unicode(false)]
        public string Crfabricante { get; set; }
        [Column("CRANO")]
        public int Crano { get; set; }
        [Required]
        [Column("CRPLACA")]
        [StringLength(7)]
        [Unicode(false)]
        public string Crplaca { get; set; }
        [Column("CRDTCADASTRO", TypeName = "smalldatetime")]
        public DateTime Crdtcadastro { get; set; }
        [Column("CRINFADICIONAIS")]
        [StringLength(255)]
        [Unicode(false)]
        public string Crinfadicionais { get; set; }

        [InverseProperty("CccdcarroNavigation")]
        public virtual ICollection<CarroCliente> CarroCliente { get; set; }
        [InverseProperty("PpcdcarroNavigation")]
        public virtual ICollection<Proposta> Proposta { get; set; }
    }
}