// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Automobilistica.Models
{
    public partial class CarroCliente
    {
        [Key]
        [Column("CCCDCARRO")]
        public int Cccdcarro { get; set; }
        [Key]
        [Column("CCCDCLIENTE")]
        public int Cccdcliente { get; set; }
        [Column("CCDTCADASTRO", TypeName = "smalldatetime")]
        public DateTime Ccdtcadastro { get; set; }
        [Column("CCSTATUS")]
        public bool? Ccstatus { get; set; }

        [ForeignKey("Cccdcarro")]
        [InverseProperty("CarroCliente")]
        public virtual Carros CccdcarroNavigation { get; set; }
        [ForeignKey("Cccdcliente")]
        [InverseProperty("CarroCliente")]
        public virtual Cliente CccdclienteNavigation { get; set; }
    }
}