// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Automobilistica.Models
{
    public partial class Enderecos
    {
        public Enderecos()
        {
            Pessoas = new HashSet<Pessoas>();
        }

        [Key]
        [Column("EDCDENDERECO")]
        public int Edcdendereco { get; set; }
        [Required]
        [Column("EDLOGRADOURO")]
        [StringLength(68)]
        [Unicode(false)]
        public string Edlogradouro { get; set; }
        [Required]
        [Column("EDNUMERO")]
        [StringLength(50)]
        [Unicode(false)]
        public string Ednumero { get; set; }
        [Required]
        [Column("EDBAIRRO")]
        [StringLength(50)]
        [Unicode(false)]
        public string Edbairro { get; set; }
        [Required]
        [Column("EDCIDADE")]
        [StringLength(58)]
        [Unicode(false)]
        public string Edcidade { get; set; }
        [Required]
        [Column("EDUF")]
        [StringLength(2)]
        [Unicode(false)]
        public string Eduf { get; set; }
        [Required]
        [Column("EDCEP")]
        [StringLength(8)]
        [Unicode(false)]
        public string Edcep { get; set; }
        [Required]
        [Column("EDCOMPLEMENTO")]
        [StringLength(50)]
        [Unicode(false)]
        public string Edcomplemento { get; set; }
        [Column("EDTIPOENDERECO")]
        public int Edtipoendereco { get; set; }

        [InverseProperty("PscdenderecoNavigation")]
        public virtual ICollection<Pessoas> Pessoas { get; set; }
    }
}