// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Automobilistica.Models
{
    public partial class Funcionarios
    {
        public Funcionarios()
        {
            Proposta = new HashSet<Proposta>();
        }

        [Key]
        [Column("FNCDFUNC")]
        public int Fncdfunc { get; set; }
        [Column("FNCDPESSOA")]
        public int Fncdpessoa { get; set; }
        [Column("FNCDCARGO")]
        public int Fncdcargo { get; set; }
        [Column("FNSALARIO")]
        public double Fnsalario { get; set; }
        [Column("FNDTCONTRATACAO", TypeName = "smalldatetime")]
        public DateTime Fndtcontratacao { get; set; }
        [Column("FNDTDESLIGAMENTO", TypeName = "smalldatetime")]
        public DateTime? Fndtdesligamento { get; set; }
        [Column("FNSTATUS")]
        public int? Fnstatus { get; set; }

        [ForeignKey("Fncdcargo")]
        [InverseProperty("Funcionarios")]
        public virtual Cargo FncdcargoNavigation { get; set; }
        [ForeignKey("Fncdpessoa")]
        [InverseProperty("Funcionarios")]
        public virtual Pessoas FncdpessoaNavigation { get; set; }
        [InverseProperty("PpcdfuncionarioNavigation")]
        public virtual ICollection<Proposta> Proposta { get; set; }
    }
}