// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Automobilistica.Models
{
    public partial class Pessoas
    {
        public Pessoas()
        {
            Cliente = new HashSet<Cliente>();
            Funcionarios = new HashSet<Funcionarios>();
        }

        [Key]
        [Column("PSCDPESSOA")]
        public int Pscdpessoa { get; set; }
        [Column("PSCDENDERECO")]
        public int Pscdendereco { get; set; }
        [Required]
        [Column("PSNOME")]
        [StringLength(255)]
        [Unicode(false)]
        public string Psnome { get; set; }
        [Required]
        [Column("PSEMAIL")]
        [StringLength(255)]
        [Unicode(false)]
        public string Psemail { get; set; }
        [Required]
        [Column("PSCGC")]
        [StringLength(15)]
        [Unicode(false)]
        public string Pscgc { get; set; }
        [Column("PSDTNASCIMENTO", TypeName = "smalldatetime")]
        public DateTime Psdtnascimento { get; set; }
        [Column("PSDTCADASTRO", TypeName = "smalldatetime")]
        public DateTime Psdtcadastro { get; set; }

        [ForeignKey("Pscdendereco")]
        [InverseProperty("Pessoas")]
        public virtual Enderecos PscdenderecoNavigation { get; set; }
        [InverseProperty("ClcdpessoaNavigation")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [InverseProperty("FncdpessoaNavigation")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}