// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Automobilistica.Models
{
    public partial class PropostaServico
    {
        [Key]
        [Column("PRCDPROPOSTA")]
        public int Prcdproposta { get; set; }
        [Key]
        [Column("PRCDSERVICO")]
        public int Prcdservico { get; set; }
        [Column("PRVALOR")]
        public double Prvalor { get; set; }

        [ForeignKey("Prcdproposta")]
        [InverseProperty("PropostaServico")]
        public virtual Proposta PrcdpropostaNavigation { get; set; }
        [ForeignKey("Prcdservico")]
        [InverseProperty("PropostaServico")]
        public virtual Servicos PrcdservicoNavigation { get; set; }
    }
}