// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Automobilistica.Models
{
    public partial class Proposta
    {
        public Proposta()
        {
            Contrato = new HashSet<Contrato>();
            PropostaServico = new HashSet<PropostaServico>();
        }

        [Key]
        [Column("PPCDPROPOSTA")]
        public int Ppcdproposta { get; set; }
        [Column("PPCDCLIENTE")]
        public int Ppcdcliente { get; set; }
        [Column("PPCDCARRO")]
        public int Ppcdcarro { get; set; }
        [Column("PPCDFUNCIONARIO")]
        public int Ppcdfuncionario { get; set; }
        [Column("PPVALOR")]
        public double Ppvalor { get; set; }
        [Column("PPDTCADASTRO", TypeName = "smalldatetime")]
        public DateTime Ppdtcadastro { get; set; }
        [Column("PPSTATUS")]
        public int? Ppstatus { get; set; }

        [ForeignKey("Ppcdcarro")]
        [InverseProperty("Proposta")]
        public virtual Carros PpcdcarroNavigation { get; set; }
        [ForeignKey("Ppcdcliente")]
        [InverseProperty("Proposta")]
        public virtual Cliente PpcdclienteNavigation { get; set; }
        [ForeignKey("Ppcdfuncionario")]
        [InverseProperty("Proposta")]
        public virtual Funcionarios PpcdfuncionarioNavigation { get; set; }
        [InverseProperty("CtcdpropostaNavigation")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [InverseProperty("PrcdpropostaNavigation")]
        public virtual ICollection<PropostaServico> PropostaServico { get; set; }
    }
}